twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        notification: '@App\Service\NotificationSystem'

    paths :
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates' : 'KnpPaginator'

when@test:
    twig:
        strict_variables: true
