vich_uploader:
    db_driver: orm
    mappings:
        user_images:
            uri_prefix: /uploads/user/image
            upload_destination: '%kernel.project_dir%/public/uploads/user/image'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        user_cv:
            uri_prefix: /uploads/user/cv
            upload_destination: '%kernel.project_dir%/public/uploads/user/cv'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        proyectogen_int:
            uri_prefix: /uploads/document/proyectogenerales
            upload_destination: '%kernel.project_dir%/public/uploads/document/proyectogenerales'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        cartaautorizacion_int:
            uri_prefix: /uploads/document/cartaautorizacion
            upload_destination: '%kernel.project_dir%/public/uploads/document/cartaautorizacion'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

        #Imagenes subidas del Post - Blog
        post_image:
            uri_prefix: /CLIO/public/uploads/user/post
            upload_destination: '%kernel.project_dir%/public/uploads/user/post'
            namer: vich_uploader.namer_uniqid
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true