#index:
#    path: /
#    controller: App\Controller\DefaultController::index

_app_login:
  path: /
  controller: Symfony\Bundle\FrameworkBundle\Controller\RedirectController::urlRedirectAction
  defaults:
    path: /login
    permanent: true

#dh_doctrine_audit:
#  resource: "@DHDoctrineAuditBundle/Controller/"
#  type: annotation